#!/usr/bin/env bash
# Script to redirect page

apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html

echo "server {
       listen 80;
       listen [::]:80;
       # server_name example.ubuntu.com;

       root /var/www/html;
       index index.html;

       location /redirect_me {
           rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
       }
}" > /etc/nginx/sites-enabled/default

service nginx restart
