#!/usr/bin/env bash
# Script to redirect page

./1-install_nginx_web_server

sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent; }' /etc/nginx/sites-available/default
service nginx restart
