#!/usr/bin/env bash
# Script page to 404 page not found

apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.html

touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
       listen 80;
       listen [::]:80;
       # server_name example.ubuntu.com;

       root /var/www/html;
       index index.html;

       location /redirect_me {
           rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
       }

       error_page 404 /404.html;
       location /404 {
           root /var/www/html;
           internal;
       }
}" > /etc/nginx/sites-enabled/default

# sed -i '/listen 80 default_server;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx restart

