#!/usr/bin/env bash
# Install and configurate nginx web server

apt-get -y update
apt-get -y install nginx

echo "Hello World" > /var/www/html/index.html

touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "server {
       listen 80;
       listen [::]:80;
       add_header X-Served-By $HOSTNAME;
       root /var/www/html;
       index index.html;

       location /redirect_me {
           rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
       }

       error_page 404 /404.html;
}" > /etc/nginx/sites-enabled/default

service nginx restart
