#!/usr/bin/env bash
# Install and configurate load balancer

apt-get update -y
apt-get install -y haproxy

echo "global
   log /dev/log local0
   log /dev/log local1 notice
   chroot /var/lib/haproxy
   stats timeout 30s
   user haproxy
   group haproxy
   daemon
defaults
log global
mode http
option httplog
option dontlognull
timeout connect 5000
timeout client 50000
timeout server 50000

#frontend
#---------------------------------
frontend http_front
bind *:80
stats uri /haproxy?stats
default_backend http_back

#round robin balancing backend http
#-----------------------------------
backend http_back
balance roundrobin
#balance leastconn
mode http
server webserver1 34.73.125.21 check    # ip_address_of_1st_centos_webserver
server webserver2 54.89.232.52 check    # ip_address_of_2nd_centos_webserver" > /etc/haproxy/haproxy.cfg

systemctl enable haproxy
systemctl start haproxy
