#!/usr/bin/env bash
# Install and configurate load balancer

apt-get update
apt-get install -y haproxy

echo "#frontend
#---------------------------------
frontend http_front
    bind *:80
    mode http
    default_backend http_back

#round robin balancing backend http
#-----------------------------------
backend http_back
    balance roundrobin
    option forwardfor
    server 3373-web-01 34.73.125.21:80 check    # ip_address_of_1st_webserver
    server 3373-web-02 54.89.232.52:80 check    # ip_address_of_2nd_webserver

listen stats
    bind *:80
    stats enable
    stats uri /haproxy?stats" >> /etc/haproxy/haproxy.cfg

service haproxy restart
