#!/usr/bin/env bash
# This scritp print 'Best School' with while and if
i=1
four=4
eigth=8
while [ $i -lt 11 ]
do
  if [ $i -eq $four ]
  then
	echo "bad luck"
  elif [ $i -eq $eigth ]
  then
	echo "good luck"
  else
  	echo "Best School"
  fi
  i=$((i + 1))
done
