#!/usr/bin/env bash
# This script change the localhost in /etc/hosts

cp /etc/hosts ~/hosts.new
sed 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# echo '127.0.0.2		' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
