#!/usr/bin/env bash
# This script displays all active IPv4 IPs
# ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' |  cut -d " " -f2
ip=$(ip address| awk '/inet/ {print $2}' | grep -v ^::1 | grep -v ^127)
